version: 2
updates:

  - package-ecosystem: "github-actions"
     # only supports updates using the GitHub repository syntax, such as actions/checkout@v3
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "elliot-100"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "elliot-100"
